import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "@/app/_components/LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          <div className="loginBtn-box">
            <LoginBtn isLoggedIn={session} />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
